version: '3.9'

services:

  db:
    image: postgres:16-alpine
    container_name: contacts_db
    restart: always
    environment:
      POSTGRES_DB: contactsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: contacts_api
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: contactsdb
      DB_USER: postgres
      DB_PASSWORD: postgres123
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: contacts_web
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata: